defaults:
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom

project_name: "main"
criterion: gini
n_estimators: 100
max_depth: null

hydra:
  run:
    dir: outputs/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: ""